const { GenerateTypings } = require('openapi-to-typescript');
const fs = require('fs');

require('dotenv').config();

if (!fs.existsSync(process.env.API_SCHEMA_PATH)){
  console.error('Missing API schema file (or API_SCHEMA_PATH not set)');
  process.exit(1);
}

const jsonFile = fs.readFileSync(process.env.API_SCHEMA_PATH);
const schema = JSON.parse(jsonFile);

GenerateTypings(schema).then(({ typeStore }) => {
  const coupleLineBreaks = new Array(19).join(' *\n');
  const discouragement = `/*\n${coupleLineBreaks} * DO NOT EDIT THIS FILE DIRECTLY! - GENERATE IT USING npm run gen-api-types INSTEAD\n${coupleLineBreaks} */\n`;
  const tslintSilencer = '/* tslint:disable */\n';
  fs.writeFileSync('src/app/types/api.ts', tslintSilencer + discouragement + '\n' + typeStore.toString());
});
