const { GenerateTypings } = require('openapi-to-typescript');
const fs = require('fs');

require('dotenv').config();

const filePath = `${process.env.BACKEND_ROOT}/fs/api.json`;

if (!fs.existsSync(filePath)){
  console.error('Missing API schema file (or BACKEND_ROOT not set)');
  process.exit(1);
}

const jsonFile = fs.readFileSync(filePath);
const schema = JSON.parse(jsonFile);

GenerateTypings(schema).then(({ typeStore }) => {
  const coupleLineBreaks = new Array(19).join(' *\n');
  const discouragement = `/*\n${coupleLineBreaks} * DO NOT EDIT THIS FILE DIRECTLY! - GENERATE IT USING npm run gen-api-types INSTEAD\n${coupleLineBreaks} */\n`;
  const tslintSilencer = '/* tslint:disable */\n';
  fs.writeFileSync('src/app/types/api.ts', tslintSilencer + discouragement + '\n' + typeStore.toString());
});
