const { GenerateTypings } = require('openapi-to-typescript');
const fs = require('fs');

require('dotenv').config();

const filePath = process.env.API_JSON_PATH;
const outputPath = 'src/app/types/api.d.ts';

if (!fs.existsSync(filePath)){
  console.error('Missing API schema file (or API_JSON_PATH not set)');
  process.exit(1);
}

const jsonFile = fs.readFileSync(filePath);
const schema = JSON.parse(jsonFile);

GenerateTypings(schema).then(typings => {
  const coupleLineBreaks = new Array(19).join(' *\n');
  const discouragement = `/*\n${coupleLineBreaks} * DO NOT EDIT THIS FILE DIRECTLY! - GENERATE IT USING npm run api:types INSTEAD\n${coupleLineBreaks} */\n`;
  const tslintSilencer = '/* tslint:disable */\n';

  fs.writeFileSync(outputPath, tslintSilencer + discouragement + '\n' + typings.toString());
});
