const fs = require('fs');
const { dedent } = require('tslint/lib/utils');

const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function createVersionsFile(filename) {
  const output = (await exec('git log -1 --date=short  --pretty="format:%h;%ct"')).stdout.toString();
  const [id, time] = output.trim().split(';');

  const content = dedent`
      // Automatically generated by ${__filename}
      export const GIT = {
        commitId: '${id}',
        commitTime: new Date(${time * 1e3}),
      };
`;

  fs.writeFileSync(filename, content.replace(/^\n/g, ''), { encoding: 'utf8' });
  console.log(`Git version information written to ${filename}`);
}

createVersionsFile('src/environments/git.ts');
