/* eslint-disable */
/*
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 * DO NOT EDIT THIS FILE DIRECTLY! - GENERATE IT USING yarn run api:types INSTEAD
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegistrationRequest {
  name: string;
  email: string;
  password: string;
}

export interface ErrorResponse {
  /**
   * An error message describing what caused the request to fail
   */
  message: string;
}

export type ValidationErrorResponse = {
  /**
   * A map containing error messages for each field that did not pass validation
   */
  errors: {
    [k: string]: string[];
  };
} & ErrorResponse;

/**
 * Role of a user
 */
export type UserRole = "guest" | "user" | "member" | "assistant" | "staff" | "admin" | "developer";

/**
 * List of supported avatar providers
 */
export type AvatarProvider = "deviantart" | "discord";

/**
 * Represents an authenticated user
 */
export interface User {
  id: number;
  name: string;
  displayName: string;
  email: string;
  role: UserRole;
  avatarUrl: string;
  avatarProvider: AvatarProvider;
}

export type PostUsersLoginRequest = LoginRequest
export type PostUsersRequest = RegistrationRequest
export interface GetSanctumCsrfCookieRequest {
}
export interface GetUsersMeRequest {
}
export interface PostUsersLogoutRequest {
}
export interface GetUsersTokensRequest {
}
export interface DeleteUsersTokensIdRequest {
  id: number
}
export interface PostUsersLoginResult {
  token?: string;
}

export type PostUsersLogin204 = any
export interface PostUsersResult {
  token?: string;
}

export type PostUsers204 = any
export type GetSanctumCsrfCookieResult = any
export type GetUsersMeResult = User;

export type PostUsersLogoutResult = any
export interface GetUsersTokensResult {}

export type DeleteUsersTokensIdResult = any